import assert from "node:assert/strict";
import { expect } from "chai";
import { deployFixture, ethers } from "./fixture.ts";

describe("LoanchPool default waterfall", function () {
  it("waits seven days, permits late payment, then haircuts Saver claims once", async function () {
    const { pool, saverA, saverB, borrower, other } = await deployFixture();
    for (const user of [saverA, saverB, borrower]) await (await pool.setIdentityVerification(user.address, true)).wait();
    await (await pool.setBorrowerRiskScore(borrower.address, 80)).wait();
    await (await pool.connect(saverA).deposit({ value: 1_000n })).wait();
    await (await pool.connect(saverB).deposit({ value: 1_000n })).wait();
    await (await pool.connect(borrower).stake({ value: 60n })).wait();
    await (await pool.connect(borrower).requestLoan(1_000n, 86400n)).wait();
    await assert.rejects(pool.connect(other).markDefault(1n), /GracePeriodActive/);
    await ethers.provider.send("evm_increaseTime", [2 * 86400]);
    await ethers.provider.send("evm_mine", []);
    await (await pool.connect(borrower).repayLoan(1n, { value: 100n })).wait();
    await assert.rejects(pool.connect(other).markDefault(1n), /GracePeriodActive/);
    await ethers.provider.send("evm_increaseTime", [7 * 86400]);
    await ethers.provider.send("evm_mine", []);
    const beforeBorrower = await ethers.provider.getBalance(borrower.address);
    await (await pool.connect(other).markDefault(1n)).wait();
    const loss = await pool.defaultLosses(1n);
    expect(loss.unpaidPrincipal).to.equal(900n);
    expect(loss.stakeUsed).to.equal(50n);
    expect(loss.reserveUsed).to.equal(0n);
    expect(loss.saverLoss).to.equal(850n);
    expect(loss.stakeReturned).to.equal(0n);
    expect(await ethers.provider.getBalance(borrower.address)).to.equal(beforeBorrower);
    expect(await pool.saverPrincipalClaims()).to.equal(1_150n);
    expect((await pool.getSaverPosition(saverA.address)).principalClaim).to.equal(575n);
    expect((await pool.getSaverPosition(saverB.address)).principalClaim).to.equal(575n);
    expect(await pool.activeLoanPrincipal()).to.equal(0n);
    expect(await pool.totalLockedStake()).to.equal(10n);
    expect((await pool.getLoan(1n)).status).to.equal(3n);
    expect((await pool.getBorrowerProfile(borrower.address)).reputation).to.equal(30n);
    expect((await pool.getBorrowerProfile(borrower.address)).blockedAfterDefault).to.equal(true);
    await assert.rejects(pool.connect(other).markDefault(1n), /InvalidLoanState/);
    await assert.rejects(pool.connect(borrower).repayLoan(1n, { value: 1n }), /InvalidLoanState/);
    await (await pool.connect(saverA).withdraw(575n)).wait();
    expect((await pool.getSaverPosition(saverB.address)).principalClaim).to.equal(575n);
    expect(await pool.liquidPoolAssets()).to.equal(575n);
    await (await pool.connect(saverB).withdraw(575n)).wait();
    expect(await ethers.provider.getBalance(await pool.getAddress())).to.equal(10n);
    await (await pool.connect(borrower).unstake(10n)).wait();
    expect(await ethers.provider.getBalance(await pool.getAddress())).to.equal(0n);
  });

  it("uses return-funded loss reserve before Saver haircut", async function () {
    const { pool, saverA, borrower, other } = await deployFixture();
    for (const user of [saverA, borrower, other]) await (await pool.setIdentityVerification(user.address, true)).wait();
    await (await pool.setBorrowerRiskScore(borrower.address, 80)).wait();
    await (await pool.setBorrowerRiskScore(other.address, 80)).wait();
    await (await pool.connect(saverA).deposit({ value: 2_000n })).wait();
    await (await pool.connect(borrower).stake({ value: 50n })).wait();
    await (await pool.connect(borrower).requestLoan(1_000n, 86400n)).wait();
    await (await pool.connect(borrower).repayLoan(1n, { value: 1_100n })).wait();
    expect(await pool.lossReserveAmount()).to.equal(5n);
    await (await pool.connect(other).stake({ value: 5n })).wait();
    await (await pool.connect(other).requestLoan(100n, 86400n)).wait();
    await ethers.provider.send("evm_increaseTime", [9 * 86400]);
    await ethers.provider.send("evm_mine", []);
    await (await pool.markDefault(2n)).wait();
    const loss = await pool.defaultLosses(2n);
    expect(loss.unpaidPrincipal).to.equal(100n);
    expect(loss.stakeUsed).to.equal(5n);
    expect(loss.stakeReturned).to.equal(0n);
    expect(loss.reserveUsed).to.equal(5n);
    expect(loss.saverLoss).to.equal(90n);
    expect(await pool.lossReserveAmount()).to.equal(0n);
    expect(await pool.saverPrincipalClaims()).to.equal(1_910n);
  });

  it("prices a new Saver deposit after loss at the reduced share value and blocks defaulted borrowers", async function () {
    const { pool, saverA, saverB, borrower, other } = await deployFixture();
    for (const user of [saverA, saverB, borrower, other]) await (await pool.setIdentityVerification(user.address, true)).wait();
    await (await pool.setBorrowerRiskScore(borrower.address, 80)).wait();
    await (await pool.connect(saverA).deposit({ value: 1_000n })).wait();
    await (await pool.connect(saverB).deposit({ value: 1_000n })).wait();
    await (await pool.connect(borrower).stake({ value: 50n })).wait();
    await (await pool.connect(borrower).requestLoan(1_000n, 86400n)).wait();
    await ethers.provider.send("evm_increaseTime", [9 * 86400]);
    await ethers.provider.send("evm_mine", []);
    await (await pool.markDefault(1n)).wait();
    expect(await pool.saverPrincipalClaims()).to.equal(1_050n);
    await (await pool.connect(other).deposit({ value: 525n })).wait();
    expect((await pool.getSaverPosition(other.address)).shares).to.equal(1_000n);
    expect((await pool.getSaverPosition(other.address)).principalClaim).to.equal(525n);
    expect((await pool.getSaverPosition(saverA.address)).principalClaim).to.equal(525n);
    expect((await pool.previewLoan(borrower.address, 100n, 86400n))[0]).to.equal(4n);
    await assert.rejects(pool.connect(borrower).requestLoan(100n, 86400n), /LoanNotEligible/);
  });

  it("returns loan stake left after unpaid principal is covered", async function () {
    const { pool, saverA, borrower } = await deployFixture();
    for (const user of [saverA, borrower]) await (await pool.setIdentityVerification(user.address, true)).wait();
    await (await pool.setBorrowerRiskScore(borrower.address, 80)).wait();
    await (await pool.connect(saverA).deposit({ value: 200n })).wait();
    await (await pool.connect(borrower).stake({ value: 5n })).wait();
    await (await pool.connect(borrower).requestLoan(100n, 86400n)).wait();
    await (await pool.connect(borrower).repayLoan(1n, { value: 97n })).wait();
    await ethers.provider.send("evm_increaseTime", [9 * 86400]);
    await ethers.provider.send("evm_mine", []);
    const before = await ethers.provider.getBalance(borrower.address);
    await (await pool.markDefault(1n)).wait();
    const loss = await pool.defaultLosses(1n);
    expect(loss.unpaidPrincipal).to.equal(3n);
    expect(loss.stakeUsed).to.equal(3n);
    expect(loss.stakeReturned).to.equal(2n);
    expect(loss.saverLoss).to.equal(0n);
    expect(await ethers.provider.getBalance(borrower.address)).to.equal(before + 2n);
  });
});
